# -*- coding: utf-8 -*-

from get_verify_code import GetVerifyCode
from login import Login
from register import Register
from logout import Logout
#from reset_passwd import ResetPasswd
#from get_uinfo import GetUInfo
#from update_uinfo import UpdateUInfo
#from publish_shop_comment import PublishShopComment
#from favour_shop import FavourShop
#from fav_shop import FavShop
#from unfav_shop import UnfavShop
#from get_my_fav_shops import GetMyFavShops
#from join_activity import JoinActivity
#from get_my_activities import GetMyActivities
#from favour_shop_comment import FavourShopComment
#from favour_goods import FavourGoods
#from get_my_sale_records import GetMySaleRecords
#from mark_shop import MarkShop
from device_status import DeviceStatus
from regen_token import RegenToken
from pet_location import PetLocation
from pet_location2 import PetLocation2
from pet_type_info import PetTypeInfo
from get_pet_info import GetPetInfo
from add_pet_info import AddPetInfo
from update_pet_info import UpdatePetInfo
from get_activity_info import GetActivityInfo
from get_sleep_info import GetSleepInfo
from summary import Summary
from pet_activity import PetActivity
from add_device_info import AddDeviceInfo
from get_device_info import GetDeviceInfo
from set_target_step import SetTargetStep
from remove_device import RemoveDeviceInfo
from set_sim_info import SetSimInfo
from set_home_wifi import SetHomeWifi
from set_home_location import SetHomeLocation
from pet_find import PetFind
from pet_walk import PetWalk
from swicth_light import SwitchLight
from get_switch_light import GetDeviceSwitchLightStatus
from get_pet_status import GetPetStatusInfo
from get_base_info import GetBaseInfo
from send_get_wifi_list_cmd import SendGetWifiListCmd
from get_wifi_list import GetWifiList
from reboot_device_cmd import RebootDeviceCmd
from agree_policy import AgreePolicy
from push_message import PushMessageCmd
from about_xmpush import SetAliasHandler,UnSetAliasHandler,SetAccountHandler,UnSetAccountHandler
from suggest import Suggest

#from get_sale_info import GetSaleInfo
#from get_sale_statist import GetSaleStatist
#from get_user_recommand_activities import GetUserRecommandActivities
